### ISSUE TITLE
Bug: Scrolling testimonial carousel on mobile is slow. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/landing-page#79]
### Describe the bug

<img width="392" alt="Screen Shot 2022-12-08 at 1 41 25 PM" src="https://user-images.githubusercontent.com/5713670/206878171-5e4c1c82-d93f-4ad2-8bf2-2c039b8a7ed4.png">

### Steps to reproduce

1. While viewing mobile scroll to the testimonials section
2. Scroll to next tweet
3. Note how slow it is.

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Tickerabucky2** [comment]
Hello @bdougie when you say slow I assume you think that the carousel background color is changed right after the next/previous slide gets in full view? This is actually done on purpose cause otherwise it is really hard to detect when to change that color. If you still find this an issue please describe the expected behavior.

**Comment by bdougie** [comment]
Sorry, meant to send a recording along with the issue. 

As seen in the recording, the scroll speed seems slow. This is an iPhone 10 pro. 


https://user-images.githubusercontent.com/5713670/207199326-69d4f588-a591-4e6b-b053-9a0f9ac3d7b8.MP4

**Comment by Tickerabucky2** [comment]
I will increase the scrolling speed and we will check if it works well.
